/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.1
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* BLE_1_bless_isr */
#define BLE_1_bless_isr__INTC_CORTEXM0P_ASSIGNED 1
#define BLE_1_bless_isr__INTC_CORTEXM0P_MUX 1u
#define BLE_1_bless_isr__INTC_CORTEXM0P_PRIORITY 3u
#define BLE_1_bless_isr__INTC_NUMBER 24u

/* I2C_1_SCB_IRQ */
#define I2C_1_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define I2C_1_SCB_IRQ__INTC_CORTEXM0P_MUX 0u
#define I2C_1_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define I2C_1_SCB_IRQ__INTC_NUMBER 36u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
