/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.1
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* scl_b */
#define scl_b_0_DRIVEMODE CY_GPIO_DM_PULLUP_IN_OFF
#define scl_b_0_INBUF_ENABLED 1u
#define scl_b_0_INIT_DRIVESTATE 1u
#define scl_b_0_INIT_MUXSEL 19u
#define scl_b_0_INPUT_SYNC 2u
#define scl_b_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define scl_b_0_NUM 0u
#define scl_b_0_PORT GPIO_PRT6
#define scl_b_0_SLEWRATE CY_GPIO_SLEW_FAST
#define scl_b_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define scl_b_DRIVEMODE CY_GPIO_DM_PULLUP_IN_OFF
#define scl_b_INBUF_ENABLED 1u
#define scl_b_INIT_DRIVESTATE 1u
#define scl_b_INIT_MUXSEL 19u
#define scl_b_INPUT_SYNC 2u
#define scl_b_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define scl_b_NUM 0u
#define scl_b_PORT GPIO_PRT6
#define scl_b_SLEWRATE CY_GPIO_SLEW_FAST
#define scl_b_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* sda_b */
#define sda_b_0_DRIVEMODE CY_GPIO_DM_PULLUP_IN_OFF
#define sda_b_0_INBUF_ENABLED 1u
#define sda_b_0_INIT_DRIVESTATE 1u
#define sda_b_0_INIT_MUXSEL 19u
#define sda_b_0_INPUT_SYNC 2u
#define sda_b_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sda_b_0_NUM 1u
#define sda_b_0_PORT GPIO_PRT6
#define sda_b_0_SLEWRATE CY_GPIO_SLEW_FAST
#define sda_b_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define sda_b_DRIVEMODE CY_GPIO_DM_PULLUP_IN_OFF
#define sda_b_INBUF_ENABLED 1u
#define sda_b_INIT_DRIVESTATE 1u
#define sda_b_INIT_MUXSEL 19u
#define sda_b_INPUT_SYNC 2u
#define sda_b_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define sda_b_NUM 1u
#define sda_b_PORT GPIO_PRT6
#define sda_b_SLEWRATE CY_GPIO_SLEW_FAST
#define sda_b_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
